Bai tap 1 Tensor co ban (Lam ngay 15/9/26)


In [ ]:
import torch

a = torch.tensor(
    [[1, 2, 3],
    [4, 5, 6]],
dtype=torch.int32
)

print("Kich thuoc:", a.shape)
print("So chieu:", a.ndim)
print("Kieu du lieu:", a.dtype)


Kich thuoc: torch.Size([2, 3])
So chieu: 2
Kieu du lieu: torch.int32


Bài 2 Tạo các Tensor thuong dung

Sự khác nhau giữa torch.rand() và torch.randn()
Lần 1 thử:
*   tensor([[0.2554, 0.9457, 0.1978, 0.3262],
        [0.5557, 0.0949, 0.2758, 0.5318],
        [0.9520, 0.4856, 0.5941, 0.9326]])
* tensor([[-1.4637, -0.6646,  0.2391,  0.6420],
        [-0.3704,  0.6880, -1.9906, -0.5062],
        [-0.3922,  0.2462, -1.1855,  2.3609]])

Lần 2 thử:
*   tensor([[0.0807, 0.6790, 0.8132, 0.6067],
        [0.3472, 0.1089, 0.9079, 0.0321],
        [0.4941, 0.1909, 0.4478, 0.2232]])
tensor([[-0.3439, -0.0919, -0.6749, -1.0449],
        [ 1.0933, -0.1935,  0.3717,  0.2723],
        [-1.2833, -0.1863,  3.2850,  0.3702]])

=> Rand sẽ sinh ra số ngẫu nhiên >0 còn => Randn sẽ có thêm số âm lẫn số dương






In [ ]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

#Một Tensor 5x5 chứa toàn giá trị 10
tensor_10 = torch.full((5, 5), 10)
print(tensor_10)

tensor([[0.1617, 0.4881, 0.8660, 0.1154],
        [0.2327, 0.8210, 0.6484, 0.0017],
        [0.6673, 0.9363, 0.5632, 0.4093]])
tensor([[-0.4202, -0.1531,  0.4367, -0.4305],
        [-0.4849,  0.4637,  0.9733,  0.6607],
        [-0.6257,  1.2296, -0.0066,  1.4532]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


Bài 3: Kiểm tra thông tin Tensor

torch.size([2,3,4]) có nghĩa là 2 ma trận trong đó mỗi ma trận có 3 hàng và 4 cột. và phương thức Size() có nghĩa là cung cấp kích thước trên từng chiều. Giúp biết được cấu trúc tổ chức dữ liệu bên trong Tensor đó như thế nào trước khi thực hiện các pháp toán

In [ ]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


Bai 4: Slicing va Indexing 

a) với a[1] thực hiện chỉ mục tại chiều đầu tiên nghĩa là chọn ra ma trận thứ 2 với index = 1 nên kết quả thu được là ma trận Thứ 2 trong tổng số 3 ma trận và có 4 hàng và 5 cột
- b) với a[1:, 2:4] thì đây là phép cắt lát trên từng chiều
- Với chiều đầu tiên (chiều 0) là (1:) thì lấy từ chỉ số 1 đến hết nghĩa là lấy ma trận thứ 2,3 bỏ ma trận 1 là chỉ số 0
- Chiều 1 (2:4) là chỉ lấy hàng 2 và trước 4 (gồm hàng 2 và 3) 
- Chiều 2 (kh viết): Mặc định giữ nguyên toàn bộ là đầy đủ 5 cột


In [10]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])
print("Hai phan tu cuoi tren chieu thu ba:")
print(a[:, :, -2:])

Original tensor:
tensor([[[-0.5560, -0.4237, -2.5960,  0.4615, -0.4851],
         [ 0.5651,  1.4733, -0.5839,  0.4033,  1.0384],
         [ 0.9134,  1.3202, -0.5204, -0.4657,  1.7597],
         [-1.8703,  1.5767, -1.2567,  0.2981,  0.7613]],

        [[-1.4070,  0.7032, -0.8829, -1.3635, -1.2456],
         [-0.5289, -0.8735,  0.4224, -2.0813,  1.5878],
         [-0.0899,  1.4312, -1.1279,  1.3534, -0.2390],
         [-0.9096, -1.5251,  0.6879, -1.1297,  0.8646]],

        [[ 2.1171,  0.4117,  0.1767, -1.9107, -0.1561],
         [-0.9767,  0.1803, -1.3415, -0.5797,  0.5739],
         [-0.1862, -1.0275,  0.7413, -0.7539, -0.2815],
         [ 0.8035, -0.2748, -0.8833,  0.5518,  0.2618]]])

Tensor a[1]:
tensor([[-1.4070,  0.7032, -0.8829, -1.3635, -1.2456],
        [-0.5289, -0.8735,  0.4224, -2.0813,  1.5878],
        [-0.0899,  1.4312, -1.1279,  1.3534, -0.2390],
        [-0.9096, -1.5251,  0.6879, -1.1297,  0.8646]])

Tensor a[1:, 2:4]:
tensor([[[-0.0899,  1.4312, -1.1279,  1.3534, -0.2

Bài 5: Resphae và Flatten

In [13]:
from torch._inductor import cudagraph_trees
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
a_reshaped = a.reshape(3, 2, 2)
print("\nReshape to 3 x 2 x 2:")
print(a_reshaped)

#Kiem tra so phan tu
print("So phan tu truoc khi reshape:", a.numel())
print("So phan tu sau khi reshape:", a_reshaped.numel())
#2. Thu reshape Tensor thanh kich thuoc 2x6
a_2x6 = a.reshape(2, 6)
print("Reshape thanh 2 x6:")
print(a_2x6)

Original:
tensor([[ 0.6532,  1.0446,  2.1661,  1.6372],
        [ 1.2030,  0.0778, -0.4809,  0.2246],
        [-0.6636, -0.8668, -0.0956,  0.6740]])

Flatten:
tensor([ 0.6532,  1.0446,  2.1661,  1.6372,  1.2030,  0.0778, -0.4809,  0.2246,
        -0.6636, -0.8668, -0.0956,  0.6740])

Reshape to 3 x 2 x 2:
tensor([[[ 0.6532,  1.0446],
         [ 2.1661,  1.6372]],

        [[ 1.2030,  0.0778],
         [-0.4809,  0.2246]],

        [[-0.6636, -0.8668],
         [-0.0956,  0.6740]]])
So phan tu truoc khi reshape: 12
So phan tu sau khi reshape: 12
Reshape thanh 2 x6:
tensor([[ 0.6532,  1.0446,  2.1661,  1.6372,  1.2030,  0.0778],
        [-0.4809,  0.2246, -0.6636, -0.8668, -0.0956,  0.6740]])
